trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 02-aks-infra/**

pool:
  name: dev-ado-agent

stages:
- stage: teraformcodevalidation
  displayName: Terraform Code Validation
  jobs:
  - job: terraform_ci
    displayName: Terraform Validation Pipeline
    steps:
    # 1. Format Check
    - task: TerraformTask@5
      displayName: Terraform Format Check
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/02-aks-infra'
        outputTo: 'console'
        customCommand: 'fmt -recursive -check'
        environmentServiceNameAzureRM: 'ado-svc-wif'

    # 2. Init (Ye step pass hoga tabhi .terraform/modules install honge)
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/02-aks-infra/environment/dev'
        backendServiceArm: 'ado-svc-wif'
        backendAzureRmResourceGroupName: 'rg_dev_axion'
        backendAzureRmStorageAccountName: 'stgdevaxion01'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.terraform.tfstate'

    # 3. Validate (Same workspace par modules mil jayenge)
    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/02-aks-infra/environment/dev'