apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app.kubernetes.io/name: myapp
spec:
  volumes:
    - name: file-share
      azureFile:
        secretName: azure-file-secret #secret yaml name
        shareName: pod-share #file share name
  containers:
    - name: nginx-container
      image: nginx:stable-alpine-slim
      ports:
        - containerPort: 80
      volumeMounts:
        - name: file-share
          mountPath: /data
