apiVersion: v1
kind: Secret
metadata:
  name: azure-file-secret
type: Opaque
stringData:
  azurestorageaccountname: mystorageaccount
  azurestorageaccountkey: "YOUR_STORAGE_ACCOUNT_KEY"

# to find storage account name and key-> goto storage account > blob storage > access keys
