apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:  
  - name: nginx-container
    image: nginx:alpine-perl
    ports:
      - containerPort: 80
  - name: firefox-container
    image:  jlesage/firefox
    ports: 
      - containerPort: 5800